export const POSTS = [
    {
        id: 0,
        title: 'Know Your Prof: Professor Jean-François Caron',
        image: '/assets/images/Caron.png',
        category: 'interview',
        featured: true,
        description: 'Meet Dr. Jean-François Caron, <strong>associate professor</strong> at SHSS and a chair of political science and international relations department. He has written a number of books in recent years on the ethics of war, disobedience in the military, technology in warfare, and federalism.',
        text: "Meet Dr. Jean-François Caron, associate professor at SHSS and a chair of political science and international relations department. He has written a number of books in recent years on the ethics of war, disobedience in the military, technology in warfare, and federalist. <br/> We have asked Prof. Caron about how he is able to remain productive and have time for his administrative duties, research, and family responsibilities. He has also given some interesting movie recommendations and shared insight into why he had chosen not to make a career in politics. <br/> <strong>APSS: What impacted you in early life to choose a career in political science?<strong/> <br/> <strong>JFC: <strong/> I am the youngest of a family of two. I have an older sister. My father was a high school teacher and he was teaching history. He was really interested in the history of wars, especially the Second World War. There were always a lot of books about this at home and I was watching documentaries with him. When the time came to choose where I wanted to study, I had to make a decision between the military college and a civilian university. At that time, I was also very interested in politics. My great-uncle was the leader of the opposition in the 70s for two years and I was very close to him. I was always talking politics with him and he was pushing me to run for office. At the same time, I was also offered a job at the House of Commons as a legislative assistant to a Member of Parliament. This is why I decided to go to the University of Ottawa. For 4 years, I studied and worked full-time on Parliament Hill. I was working 40 hours a week and taking 5 classes at the same time. I still don’t understand how I was able to do that. Going to a civilian university turned out to be a decisive life decision because if I had joined the military college, I would have had to serve in Afghanistan where 158 Canadian soldiers lost their lives. I am often thinking that if I had made the other choice, I may not be here today. My childhood also explains why my research is focused on the ethics of war."
    }
]