export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const ARTICLES_FAILED = "ARTICLES_FAILED";
export const ARTICLES_ADD = "ARTICLES_ADD";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";